org: yeukfei05
app: hk-bus-arrival-serverless
service: hk-bus-arrival-serverless

frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: ap-southeast-1
  apiName: hk-bus-arrival-serverless-prod
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
  apiGateway:
    shouldStartNameWithService: true
    description: hk bus arrival serverless prod
  architecture: arm64
  timeout: 30

functions:
  nwfbOrCtbCompany:
    handler: src/nwfbOrCtb/company/handler.company
    events:
      - http:
          path: /company
          method: get
          cors: true

  nwfbOrCtbBusRouteListScheduleJob:
    handler: src/nwfbOrCtb/busRouteListScheduleJob/handler.busRouteListScheduleJob
    events:
      # - http:
      #     path: /bus-route-list-schedule-job
      #     method: get
      #     cors: true
      - schedule: cron(0 1 1 * ? *)
    timeout: 900
    memorySize: 10000

  nwfbOrCtbBusStopListScheduleJob:
    handler: src/nwfbOrCtb/busStopListScheduleJob/handler.busStopListScheduleJob
    events:
      # - http:
      #     path: /bus-stop-list-schedule-job
      #     method: get
      #     cors: true
      - schedule: cron(0 2 1 * ? *)
    timeout: 900
    memorySize: 10000

  nwfbOrCtbBusRouteList:
    handler: src/nwfbOrCtb/busRouteList/handler.busRouteList
    events:
      - http:
          path: /bus-route-list
          method: get
          cors: true

  nwfbOrCtbBusRoute:
    handler: src/nwfbOrCtb/busRoute/handler.busRoute
    events:
      - http:
          path: /bus-route
          method: get
          cors: true

  nwfbOrCtbBusRouteStop:
    handler: src/nwfbOrCtb/busRouteStop/handler.busRouteStop
    events:
      - http:
          path: /bus-route-stop
          method: get
          cors: true

  nwfbOrCtbBusStop:
    handler: src/nwfbOrCtb/busStop/handler.busStop
    events:
      - http:
          path: /bus-stop/{busStopId}
          method: get
          cors: true

  nwfbOrCtbBusArrivalTime:
    handler: src/nwfbOrCtb/busArrivalTime/handler.busArrivalTime
    events:
      - http:
          path: /bus-arrival-time
          method: get
          cors: true

  kmbBusRouteListScheduleJob:
    handler: src/kmb/busRouteListScheduleJob/handler.busRouteListScheduleJob
    events:
      # - http:
      #     path: /kmb/bus-route-list-schedule-job
      #     method: get
      #     cors: true
      - schedule: cron(0 1 1 * ? *)
    timeout: 900
    memorySize: 10000

  kmbBusStopListScheduleJob:
    handler: src/kmb/busStopListScheduleJob/handler.busStopListScheduleJob
    events:
      # - http:
      #     path: /kmb/bus-stop-list-schedule-job
      #     method: get
      #     cors: true
      - schedule: cron(0 1 1 * ? *)
    timeout: 900
    memorySize: 10000

  kmbBusRouteList:
    handler: src/kmb/busRouteList/handler.busRouteList
    events:
      - http:
          path: /kmb/bus-route-list
          method: get
          cors: true

  kmbBusStopList:
    handler: src/kmb/busStopList/handler.busStopList
    events:
      - http:
          path: /kmb/bus-stop-list
          method: get
          cors: true

  kmbBusRoute:
    handler: src/kmb/busRoute/handler.busRoute
    events:
      - http:
          path: /kmb/bus-route
          method: get
          cors: true

  kmbBusRouteStop:
    handler: src/kmb/busRouteStop/handler.busRouteStop
    events:
      - http:
          path: /kmb/bus-route-stop
          method: get
          cors: true

  kmbBusStop:
    handler: src/kmb/busStop/handler.busStop
    events:
      - http:
          path: /kmb/bus-stop/{busStopId}
          method: get
          cors: true

  kmbBusArrivalTime:
    handler: src/kmb/busArrivalTime/handler.busArrivalTime
    events:
      - http:
          path: /kmb/bus-arrival-time
          method: get
          cors: true

  kmbBusStopArrivalTime:
    handler: src/kmb/busStopArrivalTime/handler.busStopArrivalTime
    events:
      - http:
          path: /kmb/bus-stop-arrival-time
          method: get
          cors: true

  kmbBusRouteArrivalTime:
    handler: src/kmb/busRouteArrivalTime/handler.busRouteArrivalTime
    events:
      - http:
          path: /kmb/bus-route-arrival-time
          method: get
          cors: true

plugins:
  - serverless-offline
